### ISSUE TITLE
No API for license

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#1]
The license API in inventory do not appear here?

Inventory

license : license API Show/Hide List Operations Expand Operations Raw
GET /license-info/network-device/{deviceId} Retrieves the license info for a network devices by filters
GET /license-info/network-device/{deviceId}/count Retrieves the license info for a network devices by filters
GET /network-device/license/{licenseFileName} Retrieves the list of devices with given license filenames

**Comment by ameyspatil** [comment]
Not sure, how I missed this one, but here they are 
#6
