### ISSUE TITLE
how to upload a file inline?

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#15]
Normally if I am creating a file dynamically, i do an inline upload.
files = {'fileUpload': (filename, filebody)}
do_post("file-service/file/config", files=files)

I could not see how to do this with apic.file.uploadFile ?

I might be missing something obvious?

**Comment by LiFengPro** [comment]
Currently we only support uploading a file by providing the path to the file.

```
nb_api.file.uploadFile(nameSpace='namespace', fileUpload="path/to/file")
```

Or

```
 nb_api.file.uploadFile(nameSpace='namespace', fileUpload={'filename': 'path/to/filename', 'filename2': 'file/to/filename2'})
```

Example:

```
import tempfile

filepath = tempfile.mkstemp()[1]
file_object_result = nb_api.file.uploadFile(nameSpace='sample_namespace', fileUpload=filepath).response
nb_api.file.deleteFile(fileId=file_object_result.id)
```

**Comment by ameyspatil** [comment]
@aradford123, does this https://github.com/CiscoDevNet/uniq/pull/25 work for you?

**Comment by aradford123** [comment]
That looks great..

Thanks.

**Comment by ameyspatil** [comment]
Resolved
