### ISSUE TITLE
deletePnpSiteByID does not have true/false for parameters.

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#16]
The correct call is:
deletePnpSiteByID(projectId=project_id, deleteRule=1, deleteDevice=1)

the documentation in https://github.com/CiscoDevNet/uniq/blob/master/apis/nb/clients/network_plug_and_play_client/PnpprojectApi.py
says otherwise
  deleteRule, int: Delete project rules (true) or not (false) (required)
            deleteDevice, int: Delete project devices (true) or not (false) (required)

**Comment by ameyspatil** [comment]
Resolved with https://github.com/CiscoDevNet/uniq/pull/23
