### ISSUE TITLE
parameterized file search is not available

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#17]
The APIC-EM UI allows a parameterised search for a file
https://{{apic}}:{{port}}/api/v1/file/namespace/config?name=2960-config.txt
returns
{
  "response": [
    {
      "nameSpace": "config",
      "name": "2960-client.txt",
      "downloadPath": "/file/3085587b-d226-4abd-8509-3b7756285165",
      "fileSize": "512",
      "fileFormat": "text/plain",
      "md5Checksum": "c905b02d675babf2f954ba485cc244f1",
      "sha1Checksum": "f72b936d02c0eece173179da516c78dfd3045f2f",
      "id": "3085587b-d226-4abd-8509-3b7756285165"
    }
  ],
  "version": "1.0"
}

this does not seem to be available via uniq?

Traceback (most recent call last):
  File "./create_and_upload.py", line 94, in <module>
    create_and_upload(apic, devices=DEVICES, template_file=TEMPLATE)
  File "./create_and_upload.py", line 83, in create_and_upload
    file_id = upload_file(apic, config_filename, outputText)
  File "./create_and_upload.py", line 45, in upload_file
    file_present = apic.file.getFilesByNamespace(nameSpace="config", name="2960-client.txt")
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/uniq-1.2.0-py3.4.egg/uniq/apis/nb/clients/api_client.py", line 124, in wrapper
    return list(version_function_map.values())[0](*args, **kwargs)
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/uniq-1.2.0-py3.4.egg/uniq/apis/nb/clients/file_service_client/FileApi.py", line 188, in getFilesByNamespace
    raise TypeError("Got an unexpected keyword argument '%s' to method getFilesByNamespace" % key)
TypeError: Got an unexpected keyword argument 'name' to method getFilesByNamespace

I added the parameter to getFilesByNamespace() (on my machine)

```
    allParams = ['nameSpace', 'scope', 'name']
    #allParams = ['nameSpace', 'scope']
```

and it now works.

**Comment by LiFengPro** [comment]
<img width="966" alt="screen shot 2016-07-05 at 1 24 37 pm" src="https://cloud.githubusercontent.com/assets/5546815/16599388/e3d2f432-42b6-11e6-8315-2a6a3786cd69.png">

The screenshot was taken from latest chivas build 1.2.1.440. As you can see API getFilesByNamespace only support parameters 'namespace' and 'scope'. We will open a bug to APIC-EM develop team about this. And once the api documents are fixed, we will fix this issue here.

**Comment by ameyspatil** [comment]
@aradford123 as @LiFengPro mentioned this would be a documentation bug from APIC-EM's perspective if it does not list all the available API endpoints.
Marking this issue as invalid till then.
