### ISSUE TITLE
should be able to search file namespace by id too

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#18]
https://{{apic}}:{{port}}/api/v1/file/namespace/config?id=3085587b-d226-4abd-8509-3b7756285165
{
  "response": [
    {
      "nameSpace": "config",
      "name": "2960-client.txt",
      "downloadPath": "/file/3085587b-d226-4abd-8509-3b7756285165",
      "fileSize": "512",
      "fileFormat": "text/plain",
      "md5Checksum": "c905b02d675babf2f954ba485cc244f1",
      "sha1Checksum": "f72b936d02c0eece173179da516c78dfd3045f2f",
      "id": "3085587b-d226-4abd-8509-3b7756285165"
    }
  ],
  "version": "1.0"
}

Same as earlier issue sort by name

**Comment by LiFengPro** [comment]
Same as #17

**Comment by ameyspatil** [comment]
@aradford123 as @LiFengPro mentioned this would be a documentation bug from APIC-EM's perspective if it does not list all the available API endpoints.
Marking this issue as invalid till then.
