### ISSUE TITLE
tried to pull an updated version and re-install and hit an error.

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#19]
I ended up 
rm -rf build dist
then python setup.py install

and it was fine. 

Here is the first error if I just do a git pull, then a python setup.py install
byte-compiling build/bdist.macosx-10.6-intel/egg/uniq/apis/nb/services/task/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/uniq/apis/nb/services/task/task.py to task.cpython-34.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/uniq/tests/nb/test_nb_client_manager.py to test_nb_client_manager.cpython-34.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/uniq/utils/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/uniq/utils/wait.py to wait.cpython-34.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying uniq.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying uniq.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying uniq.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying uniq.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying uniq.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
uniq.apis.nb.**pycache**.client_manager.cpython-34: module references **file**
uniq.apis.nb.clients.file_service_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.file_service_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.identity_manager_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.identity_manager_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.inventory_manager_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.inventory_manager_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.ipgeo_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.ipgeo_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.ippool_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.ippool_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.network_discovery_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.network_discovery_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.network_plug_and_play_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.network_plug_and_play_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.pki_broker_service_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.pki_broker_service_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.policy_analysis_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.policy_analysis_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.policy_manager_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.policy_manager_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.rbac_service_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.rbac_service_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.scheduler_service_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.scheduler_service_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.task_service_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.task_service_client.models.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.topology_client.**pycache**.**init**.cpython-34: module references **file**
uniq.apis.nb.clients.topology_client.models.**pycache**.**init**.cpython-34: module references **file**
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    author_email='ameyspatil@gmail.com, fengli616@gmail.com',
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Users/aradford1/Documents/work/PycharmProjects/uniq-examples/env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by LiFengPro** [comment]
The error is caused by that the compiled version of the module (the .pyc file) is corrupt. 

The solution is just like what you did, to delete existing compiled files (/dist, /build) and install again. It will let Python forcefully recompile the files.

We will update installation issues in `README` to address this issue and solution. Meanwhile, we are trying to upload our project to some public pypi repo. Once we achieve it, we could use `pip` to manage the package installation and we should not face this issue again.

**Comment by ameyspatil** [comment]
Uniq is now available on PyPi - https://pypi.python.org/pypi/uniq
So the next time while upgrading, we only have to 
pip install -U uniq

PR - https://github.com/CiscoDevNet/uniq/pull/22

**Comment by aradford123** [comment]
Awesome....

I noticed...

Thanks for this.
