### ISSUE TITLE
pip install uniq not working

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/uniq#27]
![uniq_from_git_error](https://cloud.githubusercontent.com/assets/13392790/17110947/a38c5640-529f-11e6-83e5-3a2c87e3dde1.png)
Hi

The attached image shows what happens when I try to install uniq via pip.

Did you mean to literally just use pip, or were you expecting the repository to have been cloned first? In, any case, I tried cloning too, and that didn't seem to work.

What did work was:

sudo python setup.py install

Thanks

Nathan

![uniq_pip_install_error](https://cloud.githubusercontent.com/assets/13392790/17110800/09d09be2-529f-11e6-8826-78f7e28eece6.png)

**Comment by himakoppu** [comment]
Hi Nathan,

Ubuntu 16.04 comes by default with Python 3.5.1. By using 'pip install uniq' you have installed a Python2 version of uniq. Please try 'pip3 install uniq' for installing uniq.
However you might have to first install pip3. Please use the command 'apt-get install python3-pip'. You can also refer the blog: http://askubuntu.com/questions/778052/installing-pip3-for-python3-on-ubuntu-16-04-lts-using-a-proxy - to know how to install pip3 on Ubuntu 16.04.

The sequence would be -
apt-get install python3-pip
pip3 install uniq
pip3 freeze (to know the list of installed packages)

Thanks,
Hima

**Comment by ameyspatil** [comment]
Will be tracked in  https://github.com/CiscoDevNet/uniq/issues/28
