### ISSUE TITLE
Which version of Python is required?

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/uniq#28]
Hi

The attached image shows what happens when I try uniq with Python 2.7, which did not work.

I tried Python3 also, but that would not install.

Apologies, but I am at a bit of a loss here. 

I am using Linux 4.4.0-21-generic, which is an Ubuntu 16.04 distribution.

Regards

Nathan

![uniq_issue](https://cloud.githubusercontent.com/assets/13392790/17111219/cfe0d99a-52a0-11e6-91e8-6fbd2fda4e28.png)

**Comment by himakoppu** [comment]
Hi Nathan,

Ubuntu 16.04 comes by default with Python 3.5.1. Please try '**pip3** install uniq' for installing uniq.
However you might have to first install pip3. Please use the command 'apt-get install python3-pip'. You can also refer the blog: http://askubuntu.com/questions/778052/installing-pip3-for-python3-on-ubuntu-16-04-lts-using-a-proxy  - to know how to install pip3 on Ubuntu 16.04.

The sequence would be -
apt-get install python3-pip
pip3 install uniq
pip3 freeze (to know the list of installed packages)

Thanks,
Hima

**Comment by NathanDotTo** [comment]
Hi

I was able to get uniq installed via pip3, though with a minor issue. See attached. To get around that I removed python-pip-whl, and then the pip3 install worked, and after that the uniq install and the sample scripts.

Many thanks

Nathan
![pip3_issue](https://cloud.githubusercontent.com/assets/13392790/17179058/1fee1ee8-5418-11e6-9fd6-a40aa2300cbc.png)
