### ISSUE TITLE
Issue running py.test

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#3]
I tried to run py.test on the tests directory.  I got an error message 
py.test
=========================================== test session starts ===========================================
platform darwin -- Python 2.7.10 -- py-1.4.31 -- pytest-2.7.1
rootdir: /Users/aradford1/Documents/work/PycharmProjects/uniq-examples/uniq, inifile: 
collected 0 items / 2 errors 

================================================= ERRORS ==================================================
___________________ ERROR collecting build/lib/uniq/tests/nb/test_nb_client_manager.py ____________________
build/lib/uniq/tests/nb/test_nb_client_manager.py:1: in <module>
    from unittest.mock import MagicMock
E   ImportError: No module named mock

I changed the first line to 
from mock import MagicMock

**Comment by ameyspatil** [comment]
Hi Adam,

Looks like you are using python 2.7.10 to run these tests, based on the snippet provided by you:

```
=========================================== test session starts ===========================================
platform darwin -- Python 2.7.10 -- py-1.4.31 -- pytest-2.7.1
```

To run these tests, you could directly run the below command from inside your virtualenv:
`python setup.py test`
Running that command, will install any missing test related libraries and run the tests successfully.

Closing this issue, but will add more documentation to explain the above steps.

Thanks.

**Comment by ameyspatil** [comment]
Pull Request that adds more information to the README w.r.t. running tests.
#7
