### ISSUE TITLE
No 'description' information

### ISSUE THREAD

**Issue by arikgelman** [CiscoDevNet/uniq#38]
No 'description' value information when pull interface information.

**Comment by aradford123** [comment]
I see the same issue.

https://github.com/CiscoDevNet/uniq/blob/master/apis/nb/clients/inventory_manager_client/models/DeviceIfDTO.py
does not seem to have "description" as part of the model, even though swagger does?

From Swagger:
}
DeviceIfDTO {
className (string, optional),
description (string, optional): interface description,
interfaceType (string): Interface type as Physical or Virtual,

**Comment by ameyspatil** [comment]
@aradford123, yes the model is missing the attribute.
Thanks @arikgelman for finding this bug.

We will be pushing a fix by tomorrow.

**Comment by ameyspatil** [comment]
Will be addressed with this PR
https://github.com/CiscoDevNet/uniq/pull/41
