### ISSUE TITLE
Getting more than 500 lines

### ISSUE THREAD

**Issue by arikgelman** [CiscoDevNet/uniq#51]
Hi,

The maximum number of entries returned by a GET API is 500 (default), I know there is a way to pull more information using /{start}/{end} or using offset={offset} but Is there a way to do this with UNIQ library?

Thanks in advance,
Arik

**Comment by ameyspatil** [comment]
Hi Arik,
Uniq is the python client to interact with APIC-EM's northbound REST API. So uniq can only do as much APIC-EM can. 

APIC-EM has pagination implemented in few of it's APIs, but not all.
Example: Inventory manager -> Network Device
https://github.com/CiscoDevNet/uniq/blob/master/apis/nb/clients/inventory_manager_client/NetworkdeviceApi.py#L1412

`response = client.networkdevice.getNetworkDeviceRange(startIndex=10, recordsToReturn=10, scope="All")`

Note: Uniq does not implement it's own pagination _on top_ of APIC-EM's response

If I have not understood the question incorrectly, please let me know.

**Comment by arikgelman** [comment]
Hi,

Thank you for the fast response. 

I didn't know about this syntax "getNetworkDeviceRange(startIndex=10, recordsToReturn=10, scope="All")" this looks great and will help me solve my problem.

Thanks!
