### ISSUE TITLE
see problem to log in to testACI machine

### ISSUE THREAD

**Issue by pax80** [CiscoDevNet/uniq#58]
i have an instance on ACI in a lab and i tested the code to log in, but with the actual 
apy/nb/client_manager.py i am unable to authenticate

`# resource_path = "/ticket"
        resource_path = "/aaaLogin.json"
        user_info = {
            "aaaUser": {
                "attributes": {
                    "name": self.username,
                    "pwd": self.password
                }
            }
        }
        # data = json.dumps({"username": self.username, "password": self.password})
        data = json.dumps(user_info)`

**the commented part is the original part. i replaced the path to the aaaLogin.json that will return me the response and the token that i can thake from the response in this way**

result_json = response.json()
response.json()['imdata'][0]['aaaLogin']['attributes']['token']

**Comment by rnampall** [comment]
Hi, 

Looks like you are trying with ACI/insieme or APIC-DC but Uniq is built for APIC-EM(Enterprise Module) not for ACI or APIC-DC.

**Comment by himakoppu** [comment]
Hi there. 

Uniq's api/nb/client_manager.py lets you authenticate to APIC-EM. We cannot really login to an ACI machine using APIC-EM's way of authentication, as ACI is not related to APIC_EM at all. 

APIC-DC must be what you're looking for. (https://communities.cisco.com/thread/47677?start=0&tstart=0)

**Comment by pax80** [comment]
Thanks @himakoppu, i will start writing my own module then to query the APIC DC as i couldnt find anything at the moment.
i will revert to cisco support for the full rest api documentation for the APIC DC
