### ISSUE TITLE
pip install broken for Centos7

### ISSUE THREAD

**Issue by clay584** [CiscoDevNet/uniq#63]
in setup.py the directive shows this...

    package_dir={'uniq': ''},

should be this...

    package_dir={'uniq': '.'},

This is breaking pip installs for me.

Centos 7.1 64bit
Software collections - python33
(venv2)[vagrant@localhost uniq]$ pip list
argparse (1.4.0)
cffi (1.9.1)
cryptography (1.7.1)
enum34 (1.1.6)
idna (2.2)
ipaddress (1.0.18)
lxml (3.7.2)
ncclient (0.5.3)
netaddr (0.7.19)
paramiko (2.1.1)
pip (1.4.1)
pyang (1.7.1)
pyasn1 (0.1.9)
pycparser (2.17)
requests (2.12.5)
setuptools (0.9.8)
six (1.10.0)
wheel (0.29.0)

See this for more info...

http://stackoverflow.com/questions/27408938/cant-copy-anifest-in-doesnt-exist-or-not-a-regular-file

**Comment by LiFengPro** [comment]
Please update pip and try again. 
`pip install -U pip`
We faced same issue before and it turned out to be related to pip versions. If same issue happens after updating pip, please let us know. Thanks.

**Comment by ameyspatil** [comment]
pip3 install -U setuptools
Should also help.

**Comment by clay584** [comment]
ah...thanks. I was using software collections for python33.  Didn't realize pip had a pip3 for python 3.  Thanks for your help.
