### ISSUE TITLE
support for the 1.4 command-runner API

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/uniq#69]
It is possible to add support for this new API?

thanks for resolving the other issues so quickly

**Comment by ameyspatil** [comment]
I know Cisco Live is going on, want that to run smoothly. :)

Regarding command-runner, 1.4 went on CCO last evening, so I have asked Ming to update the client by EOD tomorrow (San Jose time).

**Comment by aradford123** [comment]
that would be awesome... really appreciate the help with this.
Adam

**Comment by ameyspatil** [comment]
Uniq has been updated, and pushed to pypi with command runner apis as well.
https://pypi.python.org/pypi/uniq - uniq 1.4.0.36

**Comment by aradford123** [comment]
Got it..

Thanks so much for this.. Posting a little CLI tool using this....
